import { PGlite } from '@electric-sql/pglite';
import { pg_trgm } from '@electric-sql/pglite/contrib/pg_trgm';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite({ extensions: { pg_trgm } });
await db.exec(`
create role anon; create role authenticated;
create schema auth; create schema storage; create schema extensions;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema public,auth,storage to anon,authenticated;
grant execute on function auth.uid() to anon,authenticated;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
alter table storage.objects enable row level security;
grant select,insert,delete on storage.objects to authenticated;
create function storage.foldername(text) returns text[] language sql immutable as $$ select (string_to_array($1,'/'))[1:array_length(string_to_array($1,'/'),1)-1] $$;
`);
for (const migration of process.argv.slice(2)) await db.exec(await readFile(migration, 'utf8'));
const a = '00000000-0000-0000-0000-000000000001';
const b = '00000000-0000-0000-0000-000000000002';
await db.exec(`insert into auth.users values('${a}'),('${b}');
insert into public.profiles(id) values('${a}'),('${b}');
insert into public.ingredients(id,name,category) values('rice','Rice','Cupboard');
insert into public.pantry_items(user_id,ingredient_id,quantity,unit) values('${a}','rice',10,'g'),('${b}','rice',20,'g');
set role authenticated;select set_config('request.jwt.claim.sub','${a}',false);`);
assert.equal((await db.query('select * from public.pantry_items')).rows.length, 1);
assert.equal((await db.query(`update public.pantry_items set quantity=999 where user_id='${b}' returning *`)).rows.length, 0);
await assert.rejects(db.exec(`insert into public.pantry_items(user_id,ingredient_id,quantity,unit) values('${b}','rice',1,'g')`));
await assert.rejects(db.exec(`insert into public.pantry_items(user_id,ingredient_id,quantity,unit) values('${a}','rice',-1,'g')`));
await assert.rejects(db.exec(`insert into public.recipes(author_id,source,title,servings,minutes,status) values('${a}','cook','Fake official',2,10,'published')`));
await assert.rejects(db.exec(`insert into public.recipes(author_id,title,servings,minutes,status) values('${a}','Self published',2,10,'published')`));
const recipe = (await db.query(`insert into public.recipes(author_id,title,servings,minutes) values('${a}','Draft recipe',2,10) returning id`)).rows[0].id;
await db.exec(`insert into public.recipe_steps(recipe_id,position,title,body) values('${recipe}',1,'Prep','Wash vegetables');select set_config('request.jwt.claim.sub','${b}',false);`);
assert.equal((await db.query('select * from public.recipes')).rows.length, 0);
assert.equal((await db.query('select * from public.recipe_steps')).rows.length, 0);
await assert.rejects(db.exec(`insert into public.recipe_saves(user_id,recipe_id) values('${b}','${recipe}')`));
await assert.rejects(db.exec(`insert into storage.objects(bucket_id,name) values('scan-images','${a}/photo.jpg')`));
await db.exec(`insert into storage.objects(bucket_id,name) values('scan-images','${b}/photo.jpg');select set_config('request.jwt.claim.sub','${a}',false);`);
assert.equal((await db.query('select * from storage.objects')).rows.length, 0);
await db.exec('reset role;set role anon');
await assert.rejects(db.query('select * from public.pantry_items'));
await assert.rejects(db.query('select public.reserve_ai_call()'));
await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${a}',false);`);
await assert.rejects(db.query('select * from public.ai_daily_usage'));
for (let i=0;i<10;i++) assert.equal((await db.query('select public.reserve_ai_call() as allowed')).rows[0].allowed,true);
assert.equal((await db.query('select public.reserve_ai_call() as allowed')).rows[0].allowed,false);
await db.exec(`select set_config('request.jwt.claim.sub','${b}',false);`);
assert.equal((await db.query('select public.reserve_ai_call() as allowed')).rows[0].allowed,true);
await db.exec(`reset role;update public.ai_daily_usage set calls=99 where user_id='${a}';set role authenticated;select set_config('request.jwt.claim.sub','${b}',false);`);
assert.equal((await db.query('select public.reserve_ai_call() as allowed')).rows[0].allowed,false);
console.log('PASS: both migrations execute; 12 foundation policy assertions plus AI access, per-user and global quota assertions passed. Auth/storage are local test doubles.');
await db.close();
