import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to anon,authenticated,service_role;`);
await db.exec(await readFile('supabase/migrations/202609160001_unique_usernames.sql','utf8'));
const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002';
await db.exec(`insert into auth.users values('${a}','a@example.test','{"username":"Chef_A"}'),('${b}','b@example.test','{}');`);
await assert.rejects(db.exec(`update auth.users set raw_user_meta_data='{"username":"chef_a"}' where id='${b}'`));
await assert.rejects(db.exec(`update auth.users set raw_user_meta_data='{"username":"bad name"}' where id='${b}'`));
await db.exec(`set role anon`);
assert.equal((await db.query(`select public.username_available('CHEF_A') as available`)).rows[0].available,false);
await assert.rejects(db.query(`select * from public.account_usernames`));
await assert.rejects(db.query(`select public.username_login_email('Chef_A')`));
await assert.rejects(db.query(`select public.claim_username('Other')`));
await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${b}',false)`);
assert.equal((await db.query(`select * from public.account_usernames`)).rows.length,0);
await db.query(`select public.claim_username('Chef_B')`);
assert.equal((await db.query(`select username from public.account_usernames`)).rows[0].username,'Chef_B');
await assert.rejects(db.query(`select public.username_login_email('Chef_A')`));
await db.exec(`reset role;set role service_role`);
assert.equal((await db.query(`select public.username_login_email('CHEF_A') as email`)).rows[0].email,'a@example.test');
for(let i=0;i<10;i++) assert.equal((await db.query(`select public.reserve_username_login('test',10) as allowed`)).rows[0].allowed,true);
assert.equal((await db.query(`select public.reserve_username_login('test',10) as allowed`)).rows[0].allowed,false);
await db.close();console.log('PASS username uniqueness, metadata enforcement, ownership, email confidentiality and login limits');
