-- Original Cook preview ingredient metadata, subject to review.
begin;
insert into public.allergens(id,name) values('milk','Milk') on conflict do nothing;
insert into public.allergens(id,name) values('eggs','Eggs') on conflict do nothing;
insert into public.allergens(id,name) values('gluten','Gluten') on conflict do nothing;
insert into public.allergens(id,name) values('peanuts','Peanuts') on conflict do nothing;
insert into public.allergens(id,name) values('tree_nuts','Tree nuts') on conflict do nothing;
insert into public.allergens(id,name) values('soy','Soy') on conflict do nothing;
insert into public.allergens(id,name) values('fish','Fish') on conflict do nothing;
insert into public.allergens(id,name) values('shellfish','Shellfish') on conflict do nothing;
insert into public.allergens(id,name) values('sesame','Sesame') on conflict do nothing;
insert into public.allergens(id,name) values('celery','Celery') on conflict do nothing;
insert into public.allergens(id,name) values('mustard','Mustard') on conflict do nothing;
insert into public.allergens(id,name) values('lupin','Lupin') on conflict do nothing;
insert into public.allergens(id,name) values('molluscs','Molluscs') on conflict do nothing;
insert into public.allergens(id,name) values('sulphites','Sulphites') on conflict do nothing;
insert into public.ingredients(id,name,category,allergens_verified) values('pasta','Pasta','Cupboard',false) on conflict do nothing;
insert into public.ingredient_allergens values('pasta','gluten') on conflict do nothing;
insert into public.ingredient_aliases(ingredient_id,alias) values('pasta','spaghetti') on conflict do nothing;
insert into public.ingredient_aliases(ingredient_id,alias) values('pasta','penne') on conflict do nothing;
insert into public.ingredients(id,name,category,allergens_verified) values('tomato','Cherry tomatoes','Produce',false) on conflict do nothing;
insert into public.ingredient_aliases(ingredient_id,alias) values('tomato','tomatoes') on conflict do nothing;
insert into public.ingredient_aliases(ingredient_id,alias) values('tomato','tomato') on conflict do nothing;
insert into public.ingredients(id,name,category,allergens_verified) values('spinach','Baby spinach','Produce',false) on conflict do nothing;
insert into public.ingredient_aliases(ingredient_id,alias) values('spinach','spinach') on conflict do nothing;
insert into public.ingredient_aliases(ingredient_id,alias) values('spinach','greens') on conflict do nothing;
insert into public.ingredients(id,name,category,allergens_verified) values('garlic','Garlic','Produce',false) on conflict do nothing;
insert into public.ingredients(id,name,category,allergens_verified) values('oil','Olive oil','Cupboard',false) on conflict do nothing;
insert into public.ingredient_aliases(ingredient_id,alias) values('oil','oil') on conflict do nothing;
insert into public.ingredients(id,name,category,allergens_verified) values('lemon','Lemon','Produce',false) on conflict do nothing;
insert into public.ingredients(id,name,category,allergens_verified) values('chickpeas','Cooked chickpeas','Cupboard',false) on conflict do nothing;
insert into public.ingredient_aliases(ingredient_id,alias) values('chickpeas','chickpeas') on conflict do nothing;
insert into public.ingredient_aliases(ingredient_id,alias) values('chickpeas','garbanzo beans') on conflict do nothing;
insert into public.ingredients(id,name,category,allergens_verified) values('rice','Rice','Cupboard',false) on conflict do nothing;
insert into public.ingredient_aliases(ingredient_id,alias) values('rice','basmati') on conflict do nothing;
insert into public.ingredients(id,name,category,allergens_verified) values('egg','Eggs','Fridge',false) on conflict do nothing;
insert into public.ingredient_allergens values('egg','eggs') on conflict do nothing;
insert into public.ingredient_aliases(ingredient_id,alias) values('egg','egg') on conflict do nothing;
insert into public.ingredients(id,name,category,allergens_verified) values('feta','Feta','Fridge',false) on conflict do nothing;
insert into public.ingredient_allergens values('feta','milk') on conflict do nothing;
insert into public.ingredient_aliases(ingredient_id,alias) values('feta','cheese') on conflict do nothing;
insert into public.ingredients(id,name,category,allergens_verified) values('yogurt','Greek yogurt','Fridge',false) on conflict do nothing;
insert into public.ingredient_allergens values('yogurt','milk') on conflict do nothing;
insert into public.ingredient_aliases(ingredient_id,alias) values('yogurt','yoghurt') on conflict do nothing;
insert into public.ingredients(id,name,category,allergens_verified) values('cucumber','Cucumber','Produce',false) on conflict do nothing;
insert into public.ingredients(id,name,category,allergens_verified) values('potato','Potatoes','Produce',false) on conflict do nothing;
insert into public.ingredient_aliases(ingredient_id,alias) values('potato','potato') on conflict do nothing;
insert into public.ingredients(id,name,category,allergens_verified) values('pepper','Sweet peppers','Produce',false) on conflict do nothing;
insert into public.ingredient_aliases(ingredient_id,alias) values('pepper','bell pepper') on conflict do nothing;
insert into public.ingredients(id,name,category,allergens_verified) values('tofu','Firm tofu','Fridge',false) on conflict do nothing;
insert into public.ingredient_allergens values('tofu','soy') on conflict do nothing;
insert into public.ingredient_aliases(ingredient_id,alias) values('tofu','tofu') on conflict do nothing;
insert into public.ingredients(id,name,category,allergens_verified) values('beans','Cooked white beans','Cupboard',false) on conflict do nothing;
insert into public.ingredient_aliases(ingredient_id,alias) values('beans','cannellini beans') on conflict do nothing;
insert into public.ingredient_aliases(ingredient_id,alias) values('beans','beans') on conflict do nothing;
commit;
